// <auto-generated />
using System;
using IRMS.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IRMS.Migrations
{
    [DbContext(typeof(AppDbContextIRMS))]
    [Migration("20240428033158_H2OHero_02")]
    partial class H2OHero_02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IRMS.Model.AccionXPartida_", b =>
                {
                    b.Property<int>("AccionPartidaId")
                        .HasColumnType("int");

                    b.Property<int>("AccionId")
                        .HasColumnType("int");

                    b.Property<int>("PartidaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAxP")
                        .HasColumnType("datetime2");

                    b.HasKey("AccionPartidaId", "AccionId", "PartidaId");

                    b.HasIndex("AccionId");

                    b.HasIndex("PartidaId");

                    b.ToTable("AccionXPartidas");
                });

            modelBuilder.Entity("IRMS.Model.Accion_", b =>
                {
                    b.Property<int>("AccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccionId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DispositivoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreAccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccionId");

                    b.ToTable("Acciones");
                });

            modelBuilder.Entity("IRMS.Model.Clima_", b =>
                {
                    b.Property<int>("ClimaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClimaId"));

                    b.Property<string>("EfectoClima")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreClima")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClimaId");

                    b.ToTable("Climas");
                });

            modelBuilder.Entity("IRMS.Model.Cultivo_", b =>
                {
                    b.Property<int>("CultivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CultivoId"));

                    b.Property<string>("CultivoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DispositivoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NivelAgua")
                        .HasColumnType("int");

                    b.HasKey("CultivoId");

                    b.ToTable("Cultivos");
                });

            modelBuilder.Entity("IRMS.Model.Dispositivo_", b =>
                {
                    b.Property<int>("DispositivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DispositivoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreDispositivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDispositivoId")
                        .HasColumnType("int");

                    b.HasKey("DispositivoId");

                    b.ToTable("Dispositivos");
                });

            modelBuilder.Entity("IRMS.Model.Granja_", b =>
                {
                    b.Property<int>("GranjaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GranjaId"));

                    b.Property<int>("ClimaId")
                        .HasColumnType("int");

                    b.Property<int>("CultivoId")
                        .HasColumnType("int");

                    b.Property<int>("CultvoId")
                        .HasColumnType("int");

                    b.Property<string>("Dificultad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreGranja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SistemaRiego")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GranjaId");

                    b.HasIndex("ClimaId");

                    b.HasIndex("CultivoId");

                    b.ToTable("Granjas");
                });

            modelBuilder.Entity("IRMS.Model.Jugador_", b =>
                {
                    b.Property<int>("JugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JugadorId"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JugadorId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("IRMS.Model.Partida_", b =>
                {
                    b.Property<int>("PartidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartidaId"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGuardado")
                        .HasColumnType("datetime2");

                    b.Property<int>("GranjaId")
                        .HasColumnType("int");

                    b.Property<int>("JugadorId")
                        .HasColumnType("int");

                    b.Property<string>("PartidaEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Puntuacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartidaId");

                    b.HasIndex("GranjaId");

                    b.HasIndex("JugadorId");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("IRMS.Model.TipoDispositivo_", b =>
                {
                    b.Property<int>("TipoDispositivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoDispositivoId"));

                    b.Property<string>("NombreTipoDispositivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoDispositivoId");

                    b.ToTable("TipoDispositivos");
                });

            modelBuilder.Entity("IRMS.Model.AccionXPartida_", b =>
                {
                    b.HasOne("IRMS.Model.Accion_", "Accion")
                        .WithMany()
                        .HasForeignKey("AccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRMS.Model.Partida_", "Partida")
                        .WithMany()
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accion");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("IRMS.Model.Granja_", b =>
                {
                    b.HasOne("IRMS.Model.Clima_", "Clima")
                        .WithMany()
                        .HasForeignKey("ClimaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRMS.Model.Cultivo_", "Cultivo")
                        .WithMany()
                        .HasForeignKey("CultivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clima");

                    b.Navigation("Cultivo");
                });

            modelBuilder.Entity("IRMS.Model.Partida_", b =>
                {
                    b.HasOne("IRMS.Model.Granja_", "Granja")
                        .WithMany()
                        .HasForeignKey("GranjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRMS.Model.Jugador_", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Granja");

                    b.Navigation("Jugador");
                });
#pragma warning restore 612, 618
        }
    }
}
