// <auto-generated />
using System;
using IRMS.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IRMS.Migrations
{
    [DbContext(typeof(AppDbContextIRMS))]
    [Migration("20240428033535_H2OHero_03")]
    partial class H2OHero_03
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IRMS.Model.Accion", b =>
                {
                    b.Property<int>("AccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccionId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DispositivoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreAccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccionId");

                    b.ToTable("Accion");
                });

            modelBuilder.Entity("IRMS.Model.AccionXPartida", b =>
                {
                    b.Property<int>("AccionPartidaId")
                        .HasColumnType("int");

                    b.Property<int>("AccionId")
                        .HasColumnType("int");

                    b.Property<int>("PartidaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAxP")
                        .HasColumnType("datetime2");

                    b.HasKey("AccionPartidaId", "AccionId", "PartidaId");

                    b.HasIndex("AccionId");

                    b.HasIndex("PartidaId");

                    b.ToTable("AccionXPartida");
                });

            modelBuilder.Entity("IRMS.Model.Clima", b =>
                {
                    b.Property<int>("ClimaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClimaId"));

                    b.Property<string>("EfectoClima")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreClima")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClimaId");

                    b.ToTable("Clima");
                });

            modelBuilder.Entity("IRMS.Model.Cultivo", b =>
                {
                    b.Property<int>("CultivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CultivoId"));

                    b.Property<string>("CultivoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DispositivoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NivelAgua")
                        .HasColumnType("int");

                    b.HasKey("CultivoId");

                    b.ToTable("Cultivo");
                });

            modelBuilder.Entity("IRMS.Model.Dispositivo", b =>
                {
                    b.Property<int>("DispositivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DispositivoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreDispositivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDispositivoId")
                        .HasColumnType("int");

                    b.HasKey("DispositivoId");

                    b.ToTable("Dispositivo");
                });

            modelBuilder.Entity("IRMS.Model.Granja", b =>
                {
                    b.Property<int>("GranjaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GranjaId"));

                    b.Property<int>("ClimaId")
                        .HasColumnType("int");

                    b.Property<int>("CultivoId")
                        .HasColumnType("int");

                    b.Property<int>("CultvoId")
                        .HasColumnType("int");

                    b.Property<string>("Dificultad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreGranja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SistemaRiego")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GranjaId");

                    b.HasIndex("ClimaId");

                    b.HasIndex("CultivoId");

                    b.ToTable("Granja");
                });

            modelBuilder.Entity("IRMS.Model.Jugador", b =>
                {
                    b.Property<int>("JugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JugadorId"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JugadorId");

                    b.ToTable("Jugador");
                });

            modelBuilder.Entity("IRMS.Model.Partida", b =>
                {
                    b.Property<int>("PartidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartidaId"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGuardado")
                        .HasColumnType("datetime2");

                    b.Property<int>("GranjaId")
                        .HasColumnType("int");

                    b.Property<int>("JugadorId")
                        .HasColumnType("int");

                    b.Property<string>("PartidaEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Puntuacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartidaId");

                    b.HasIndex("GranjaId");

                    b.HasIndex("JugadorId");

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("IRMS.Model.TipoDispositivo", b =>
                {
                    b.Property<int>("TipoDispositivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoDispositivoId"));

                    b.Property<string>("NombreTipoDispositivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoDispositivoId");

                    b.ToTable("TipoDispositivo");
                });

            modelBuilder.Entity("IRMS.Model.AccionXPartida", b =>
                {
                    b.HasOne("IRMS.Model.Accion", "Accion")
                        .WithMany()
                        .HasForeignKey("AccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRMS.Model.Partida", "Partida")
                        .WithMany()
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accion");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("IRMS.Model.Granja", b =>
                {
                    b.HasOne("IRMS.Model.Clima", "Clima")
                        .WithMany()
                        .HasForeignKey("ClimaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRMS.Model.Cultivo", "Cultivo")
                        .WithMany()
                        .HasForeignKey("CultivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clima");

                    b.Navigation("Cultivo");
                });

            modelBuilder.Entity("IRMS.Model.Partida", b =>
                {
                    b.HasOne("IRMS.Model.Granja", "Granja")
                        .WithMany()
                        .HasForeignKey("GranjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRMS.Model.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Granja");

                    b.Navigation("Jugador");
                });
#pragma warning restore 612, 618
        }
    }
}
